name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          sudo apt-get update -y || true
          sudo apt-get install -y build-essential cmake ninja-build || true
          brew install cmake ninja || true

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install ninja cmake mingw -y
          echo "CMAKE_GENERATOR=Ninja" >> $env:GITHUB_ENV
          echo "PATH=$env:PATH;C:\ProgramData\chocolatey\bin;C:\Program Files\CMake\bin;C:\mingw\bin" >> $env:GITHUB_ENV

      - name: Configure (CMake)
        run: cmake -S . -B build -G "Ninja"

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --output-on-failure
